# Generated by Django 4.2.3 on 2023-07-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anime_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('anime_href', models.CharField(max_length=200)),
                ('img_href', models.CharField(max_length=200)),
                ('season', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=200)),
            ],
        ),
    ]
